[package]
name = "cashu_escrow_client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nostr-sdk = { version = "0.34.0", features = [] }
cdk = "0.3.0"
anyhow = "1.0.86"
rand = "0.8.5"
serde_json = "1.0.117"
sha2 = "0.10.8"

cashu_escrow_common = { path = "../common" }
log = "0.4.22"
