[package]
name = "cashu_escrow_client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nostr-sdk = { workspace = true, features = [] }
cdk = { workspace = true }
anyhow = { workspace = true }
log = { workspace = true }
rand = "0.8.5"
serde_json = "1.0.117"
sha2 = "0.10.8"

cashu_escrow_common = { path = "../common" }
