[package]
name = "cashu_escrow_common"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nostr-sdk = { workspace = true, features = [] }
cdk = { workspace = true }
anyhow = { workspace = true }
log = { workspace = true }
tokio = "1.38.0"
serde = "1.0.203"
serde_json = "1.0.117"
