[package]
name = "cashu_escrow_common"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nostr-sdk = { version = "0.34.0", features = [] }
cdk = "0.1.1"
anyhow = "1.0.86"
tokio = "1.38.0"
serde = "1.0.203"
serde_json = "1.0.117"